### ISSUE TITLE
 Action method not found! jbconfig :: zoohack()

### ISSUE THREAD

**Issue by planb-by** [JBZoo-CCK/JBZoo#34]
Привет!
Отдельное спасибо и безграничный респект вам!

Но есть один косяк.
При попытке зайти в Zoo Оптимизатор (Хаки) появляется ошибка 500 - Action method not found! jbconfig :: zoohack().

Хелп!

**Comment by SmetDenis** [comment]
Спасибо!
@CB9TOIIIA Обещал исправить это на досуге.

**Comment by CB9TOIIIA** [comment]
Я подправлю, вначале надо интеграцию с МойСклайд дописать.

**Comment by CB9TOIIIA** [comment]
fix https://github.com/JBZoo/JBZoo/releases/tag/4.0.8
