### ISSUE TITLE
Less Error (JBZoo): .transition is undefined in clientarea.less

### ISSUE THREAD

**Issue by kokgreat** [JBZoo-CCK/JBZoo#36]
Добрый день.

При попытке просмотреть историю заказов (Front-End) вылетает ошибка:
`Less Error (JBZoo):
.transition is undefined in C:/OpenServer/domains/autote082018/media/zoo/applications/jbuniversal/assets/less/cart/clientarea.less
`
ps: адрес страницы /index.php?option=com_zoo&controller=clientarea&task=orders&Itemid=244

Joomla: 3.8.12 JBZoo: 4.0.2 GNU GPL (Community Edition) by SmetDenis Zoo: 3.3.32. 

Версия PHP 5.6.23

**Comment by exmmth** [comment]
Были ли какие-то изменения внесены? в частности это касается файлов
media\zoo\applications\jbuniversal\assets\less\misc\aliases.less (тут и есть недостающий вам .transition)
media\zoo\applications\jbuniversal\assets\less\jbzoo.less (тут подключается файл aliases)

**Comment by kokgreat** [comment]
т.к. была платная версия JBZoo: 2.2.7 Pro, то провёл следующие работы:
1. Обновил до GPL
2. Установил jbzoo_update.zip
3. Переиндексация и чистка БД средствами zoo
4. Обновление до zoo 3.3.32
5. Обновление языкового пакета zoo 3.3.32

Напрямую руками в файлы не лазил после jbzoo_update.zip, ну может раньше что-то менял. После обновления до JBZoo: 4.0.2 GNU GPL полагаю обновились и less файлы.

**Comment by kokgreat** [comment]
В aliases.less есть запись:
` .transition(...)                { #transition   > .simple(@arguments);      }`

В jbzoo.less есть запись:
`@import "misc/aliases";`

**Comment by kokgreat** [comment]
Что удивительно, в логах Апача OpenServera под Win7 нет никаких записей об ошибках, не могу найти корректную запись об ошибке, где конкретно сломалось.

Если в clientarea.less удаляю строки про .transition, то всё ок.

**Comment by kovalchyk** [comment]
Проблема проявляется в случае существующих заказов. Пользователь у которого нет истории покупок видит странице нормально.

Проблема пока не решена как я понимаю?

**Comment by SmetDenis** [comment]
@kovalchyk Попробуйте убрать .transition из файла less.

**Comment by kokgreat** [comment]
убрал .transition из файла less - всё стало нормально работать.
