### ISSUE TITLE
The <select> tag has a double id attribute

### ISSUE THREAD

**Issue by avsob** [JBZoo-CCK/JBZoo#51]
Добрый день.

При выводе тегов <select> атрибут id генерируется дважды.

На [demo](http://demo.jbzoo.com/sites/phones/) эта ошибка тоже проявляется:

`
<select **id="jbfilter-id-5bb44b83-a5d7-4f8f-a73c-982906b9cb53-e1d3609b-7f2c-40c3-98dc-a6a072db38f0"** name="e[5bb44b83-a5d7-4f8f-a73c-982906b9cb53][e1d3609b-7f2c-40c3-98dc-a6a072db38f0][id]" **id="jbfilter-id-5bb44b83-a5d7-4f8f-a73c-982906b9cb53-e1d3609b-7f2c-40c3-98dc-a6a072db38f0"** class="element-select element-tmpl-_auto_">
`

**Comment by fiction13** [comment]
Прошелся по демо и актуальным сайтам. Проблемы не увидел. Закрываем?

**Comment by avsob** [comment]
Проблема на демо(http://demo.jbzoo.com/sites/phones/ ) есть. 
Смотри исходный код страницы(не через F12). Поиск по коду можно сделать по "jbfilter-id-5bb44b83-a5d7-4f8f-a73c-982906b9cb53-e1d3609b-7f2c-40c3-98dc-a6a072db38f0". 

`<select id="jbfilter-id-5bb44b83-a5d7-4f8f-a73c-982906b9cb53-e1d3609b-7f2c-40c3-98dc-a6a072db38f0" name="e[5bb44b83-a5d7-4f8f-a73c-982906b9cb53][e1d3609b-7f2c-40c3-98dc-a6a072db38f0][id]" id="jbfilter-id-5bb44b83-a5d7-4f8f-a73c-982906b9cb53-e1d3609b-7f2c-40c3-98dc-a6a072db38f0" class="element-select element-tmpl-_auto_">`

**Comment by fiction13** [comment]
Извиняюсь, проблему увидел, посмотрю
