### ISSUE TITLE
0 Call to undefined method JBZooSystemPlugin::onBeforeRespond()

### ISSUE THREAD

**Issue by nextontext** [JBZoo-CCK/JBZoo#52]
Здравствуйте! Подскажите пожалуйста, обновил Joomla до 3.9, получил:
0 Call to undefined method JBZooSystemPlugin::onBeforeRespond()

Теперь не могу ничего обновить, постоянно это сообщение, пробовал отключать JBZooSystemPlugin в плагинах, слетает вся админка.

Спасибо!

**Comment by CB9TOIIIA** [comment]
Добрый, Joomla 3.9 сегодня только вышла, поэтому потребуется время для фикса для новой версии. Сейчас идет обсуждение в ветке: http://forum.jbzoo.com/topic/21679-oshibka-plagina-jbzoo-pri-obnovlenie-joomla-39/

**Comment by kulbabskyy** [comment]
подтверждаю, тоже словил после обновления до 3.9

**Comment by Blackspaceta** [comment]
Аналогичная ошибка появилась один раз при обновлении Joomla с 3.8.7 до 3.9.
Сайт и админка работают без проблем, а данная ошибка не высвечивалась более нигде кроме Extensions -> Manage -> Update. То есть обновить через админку более ничего не получается.
Но, заглянув в ветку http://forum.jbzoo.com/topic/21679-oshibka-plagina-jbzoo-pri-obnovlenie-joomla-39/ как и указывал CB9TOIIIA я нашёл решение.

У меня JBZoo 2.3.1, до обновления Joomla установил JBZoo-2-GPL-patches-master для своей версии JBZoo.

**Comment by CB9TOIIIA** [comment]
fix: https://github.com/JBZoo/JBZoo/releases/tag/4.10.2
