### ISSUE TITLE
liqpay.com to liqpay.ua

### ISSUE THREAD

**Issue by CB9TOIIIA** [JBZoo-CCK/JBZoo#68]
liqpay.com to liqpay.ua

**Comment by CB9TOIIIA** [comment]
https://github.com/JBZoo/JBZoo/blob/abf325fec1d1913b8a65253360ffbac22a212305/src/packages/jbuniversal/jbuniversal/cart-elements/payment/liqpay/liqpay.php#L31

**Comment by CB9TOIIIA** [comment]
@fiction13 ты в PR это же сделаешь? @fiction13

**Comment by fiction13** [comment]
> @fiction13 ты в PR это же сделаешь? @fiction13

Добавлю, да
