### ISSUE TITLE
JString::str_ireplace заменить на str_ireplace (php 7.3)

### ISSUE THREAD

**Issue by CB9TOIIIA** [JBZoo-CCK/JBZoo#72]
В файле /media/zoo/applications/jbuniversal/framework/helpers-std/string.php

**Comment by fiction13** [comment]
Была проблема с заменой фразы "42 мм" во фразу "42-mм".

Проблему подтвердить не удалось на Joomla 3.9.19, JBZoo 4.11 и php 7.3.

Предлагаю закрыть. Если обнаружится снова - откроем и будем изучать подробнее.
