### ISSUE TITLE
Добавить jbgalleryimage

### ISSUE THREAD

**Issue by CB9TOIIIA** [JBZoo-CCK/JBZoo#73]
https://github.com/JBZoo/JBZoo/blob/fe7e862679d2da45efde25e0a729a817149eefc0/src/packages/jbuniversal/jbuniversal/framework/helpers/jbyml.php#L506

if ($element->config->type == 'jbimage' || $element->config->type == 'jbgalleryimage') {

**Comment by CB9TOIIIA** [comment]
В ядро? и элементы тоже @fiction13

**Comment by fiction13** [comment]
> В ядро? и элементы тоже @fiction13

Да, добавлю
