### ISSUE TITLE
$isAjax возможно баг в модификаторах

### ISSUE THREAD

**Issue by CB9TOIIIA** [JBZoo-CCK/JBZoo#74]
**Screenshots**
![image](https://user-images.githubusercontent.com/1074710/77419916-3a803400-6dda-11ea-81db-dd54195f88c0.png)

![image](https://user-images.githubusercontent.com/1074710/77419932-3f44e800-6dda-11ea-9e5e-9d88a007c00e.png)

![image](https://user-images.githubusercontent.com/1074710/77419940-423fd880-6dda-11ea-8ea9-1029f07b7961.png)

```
 if ($isAjax && $isValid && $isChange) {
          

            $list = $jbPrice->getList();
            if (($itemData && $itemData->get('quantity', 1) >= $quantity) ||
                (!$itemData && $list->quantity >= $quantity)
            ) {
                return $this->_order->val($this->config->get('rate'));
            }
        }
```

to work on site client:

```
 if ($isValid && $isChange) {

            $list = $jbPrice->getList();
            if (($itemData && $itemData->get('quantity', 1) >= $quantity) ||
                (!$itemData && $list->quantity >= $quantity)
            ) {
                return $this->_order->val($this->config->get('rate'));
            }
        }
```

**Comment by CB9TOIIIA** [comment]
Что скажешь? был у меня такой баг @fiction13

**Comment by fiction13** [comment]
Проверю, похоже на правду

**Comment by CB9TOIIIA** [comment]
![image](https://user-images.githubusercontent.com/1074710/93196750-7d044700-f753-11ea-88a5-25e767bcfebd.png)

**Comment by vvkalinin81** [comment]
Confirmed, а дальше? )
