### ISSUE TITLE
?f=1 (дубли категорий)

### ISSUE THREAD

**Issue by CB9TOIIIA** [JBZoo-CCK/JBZoo#76]
Требуется убрать выбор пункта меню в модуле `mod_jbzoo_category`
Модуль - Вкладка "настройка категорий" - "Пункт меню" 
http://forum.jbzoo.com/topic/10772-seo-sef-urlf1/?hl=f

http://llfl.ru/mau0ez

![image](https://user-images.githubusercontent.com/1074710/80198942-73096c80-8629-11ea-9818-279fd9c7a326.png)

это вопрос к zoo

`administrator\components\com_zoo\helpers\route.php`

![image](https://user-images.githubusercontent.com/1074710/80200084-c9c37600-862a-11ea-9a81-471566bca55f.png)

Может опционально фикс:

`$catUrl = str_replace('?f=1','',$catUrl);`

**Comment by fiction13** [comment]
Я считаю, что если не нужно получать ссылки с f=1, то не надо выбирать пункт меню, всего делов.

Есть смысл добавлять настройку с вырезом **&f=1**?

**Comment by CB9TOIIIA** [comment]
> Я считаю, что если не нужно получать ссылки с f=1, то не надо выбирать пункт меню, всего делов.
> 
> Есть смысл добавлять настройку с вырезом **&f=1**?

Я за опциональный выбор и вырезку.  Ну либо - красный прямо подписать, чтобы не было дублей f1 - не выбирай пункт меню :)

**Comment by fiction13** [comment]
> Я за опциональный выбор и вырезку. Ну либо - красный прямо подписать, чтобы не было дублей f1 - не выбирай пункт меню :)

Ну давай попробуем вырезать насильно, я в принципе не вижу ничего плохого в этом. Просто добавлять опцию - это надо объяснять, что за опция, что за f=1, почему оно мешает, зачем использовать опцию - очень много вопросов от рядового пользователя. Сложнаааа ;-)
